### ISSUE TITLE
bug: Version 24.7.2 appears to break UI access to Splunk

### ISSUE THREAD

**Issue by ceejx** [requestly/requestly#1904]
### Describe your issue?

After today's released update, I received multiple reports from Splunk users of broken access to Splunk UI with several JavaScript errors. After investigating, we determined disabling the requestly add-on (even with no rules present), allows access back in to Splunk. This was tested on the latest version of both Crome and Edge browsers.

### Repro steps

1. Install Requestly
2. Restart browser
3. Navigate to Splunk UI

### What Requestly tool were you using?

- [X] Extension
- [ ] Desktop-App
- [ ] Android SDK
- [ ] Selenium

### Your Environment

MacOS 14.5, Chrome 126.0.6478.127 (Official Build) (arm64)

### Requestly Version

24.7.2

### Error screenshot

Uncaught SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at config?autoload=1:1:74
    at config?autoload=1:1:97Understand this error
swa.js:1406 Uncaught TypeError: Cannot read properties of undefined (reading 'VERSION_LABEL')
    at new Event (swa.js:1406:63)
    at EventQueue._createEvent (swa.js:1705:14)
    at EventQueue.push (swa.js:1622:24)
    at Object.PageHandler [as handler] (swa.js:1379:10)
    at swa.js:2126:21
    at Array.forEach (<anonymous>)
    at SWACore.loadHandlers (swa.js:2121:34)
    at new SWACore (swa.js:2086:10)
    at HTMLScriptElement.onLoadSwa (xxxxx masked url xxxxxx)Understand this error
/en-US/undefined/static/build/api/get_theme.js:1 
        
        
       Failed to load resource: the server responded with a status of 404 (Not Found)Understand this error
search:1 Refused to execute script from '*masked*/en-US/undefined/static/build/api/get_theme.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.Understand this error
load_themed_page.js:1 Unable to load theme API.
r @ load_themed_page.js:1Understand this error
load_themed_page.js:1 Uncaught ReferenceError: __DEV__ is not defined
    at r (load_themed_page.js:1:7216)
    at load_themed_page.js:1:7429
    at _ (load_themed_page.js:6:386)
    at u.onload.u.onerror.u.onreadystatechange (load_themed_page.js:6:884)Understand this error
swa.js:1406 Uncaught TypeError: Cannot read properties of undefined (reading 'VERSION_LABEL')
    at new Event (swa.js:1406:63)
    at EventQueue._createEvent (swa.js:1705:14)
    at EventQueue.push (swa.js:1622:24)
    at swa.js:1323:12

**Comment by wrongsahil** [comment]
Hey @ceejx . We are working on a feature to add blocklist domains for these cases only https://github.com/requestly/requestly/issues/1898. RIght now only solution i see is by disabling extension for now. 

Is there a URL where i can test this behaviour? This would help me debugging it further

**Comment by sachinjain024** [comment]
Thanks, @ceejx for reporting this. Do you happen to remember if this issue is happening in the latest version only or happened earlier as well?

**Comment by sachinjain024** [comment]
@wrongsahil Should we create a `manifest-v3` label as well?

**Comment by wrongsahil** [comment]
@sachinjain024 Its already there. Added to the issue

**Comment by wrongsahil** [comment]
Hey @ceejx, Can you try out this beta build https://chromewebstore.google.com/detail/requestly-intercept-modif/hflhkgcfclhibpldaeppcmcnfkkndmhf

As this is beta track, this is not that stable and might contain some other bugs. So please use this only for sometime until we fix the issue in prod

**Comment by ceejx** [comment]
Sahil, I will test this out today.

Gary

**Comment by ceejx** [comment]
@sachinjain024 getting some updated info from my users, one reports that this started on MS Edge browser about 2 weeks ago. I'm trying to lock down a specific date when he started seeing the problem.

**Comment by sachinjain024** [comment]
@ceejx We have found the fix for this issue. We are going to roll this out over the weekend.

**Comment by wrongsahil** [comment]
Hey @ceejx . v24.7.7 is available in the chrome store now. Can you please manually update the extension using these [steps](https://developers.requestly.com/guides/update-requestly-extension/) and see if this issue is fixed or not

**Comment by ceejx** [comment]
hey @wrongsahil sorry was out the last several days for the 4th holiday, will test this today and update you.

**Comment by ceejx** [comment]
so far initial tests from my browser it seems to be fixed, waiting for a couple users with the issue to test for me

**Comment by wrongsahil** [comment]
Really happy to know everything is working fine now :D

Closing this issue for now. Feel free open it if you face the issue again.

**Comment by ceejx** [comment]
@wrongsahil thanks for all of your help and for the quick resolution!
