### ISSUE TITLE
bug: Can't start

### ISSUE THREAD

**Issue by vladyxd** [requestly/requestly#2320]
### Describe your issue?

Hi. So I have tried for the past several days to get this working, but no progress so far.
Errors:

2:27:39 PM [vite] Pre-transform error: Failed to resolve entry for package "@requestly/requestly-core". The package may have incorrect main/module/exports specified in its package.json. (x839)

in console

and

[plugin:vite:import-analysis] Failed to resolve entry for package "@requestly/requestly-core". The package may have incorrect main/module/exports specified in its package.json.

on browser

### Repro steps

I cloned the repo
`cd requestly` then `npm i`, all good
`cd app` and `npm i`, everything good.
Upon `npm start` in `app` I get hundreds of errors as mentioned in the issue.

### What Requestly tool were you using?

- [ ] Extension
- [X] Desktop-App
- [ ] Android SDK
- [ ] Selenium

### Your Environment

Windows 11, latest

### Requestly Version

v24.5.16-12.26

### Error screenshot

![image](https://github.com/user-attachments/assets/38b9a801-dc8f-4103-a167-e5aeab527d80)
![image](https://github.com/user-attachments/assets/a0a6522b-7129-4384-a57f-16459a50b9d5)

**Comment by vladyxd** [comment]
> ot folder

Hi there, I did so and the same errors keep occuring. Also I got this message after `build`ing
Class not registered 
Error code: Bash/CallMsi/Install/REGDB_E_CLASSNOTREG

And also:
index.js → dist/requestly-core.cjs.js, dist/requestly-core.esm.js...
[!] Error: Could not resolve './common/rule-processor/dist/' from index.js
Error: Could not resolve './common/rule-processor/dist/' from index.js
    at error (C:\Users\chesc\Desktop\Projects\Requestify\requestly\node_modules\rollup\dist\shared\rollup.js:198:30)
    at ModuleLoader.handleResolveId (C:\Users\chesc\Desktop\Projects\Requestify\requestly\node_modules\rollup\dist\shared\rollup.js:22287:24)       
    at C:\Users\chesc\Desktop\Projects\Requestify\requestly\node_modules\rollup\dist\shared\rollup.js:22250:26

**Comment by vladyxd** [comment]
Nevermind, got it closed! It was an issue with WSL on my side!
