### ISSUE TITLE
bug: Fresh Mac install, got Javascript error (missing cert)

### ISSUE THREAD

**Issue by davidalejandroaguilar** [requestly/requestly#652]
### Describe your issue?

```
Uncaught Exception:
Error: ENOENT: no such file or directory, open '/Users/david/Library/Application Support/Requestly/.tmp/certs/ca.pem'
at Object.openSync (node:fs:600:3)
at Object.func [as openSync] (node:electron/js2c/asar_bundle:2:1822)
at readFileSync (node:fs:468:35)
at t.readFileSync (node:electron/js2c/asar_bundle:2:9165)
at t.createOrUpdateAxiosInstance (/Applications/Requestly.app/Contents/Resources/app.asar/dist/main/main.js:14:674445)
at IpcMainImpl.<anonymous> (/Applications/Requestly.app/Contents/Resources/app.asar/dist/main/main.js:14:683630)
at IpcMainImpl.emit (node:events:513:28)
at EventEmitter.<anonymous> (node:electron/js2c/browser_init:2:80713)
at EventEmitter.emit (node:events:513:28)
```

### Repro steps

1. Download Mac app.
2. Open file.
3. Drag app to Applications folder.
4. Open from Applications folder.

### What Requestly tool were you using?

- [ ] Extension
- [X] Desktop-App
- [ ] Android SDK
- [ ] Selenium

### Your Environment

macOS Monterrey 12.6

### Requestly Version

1.5.2

**Comment by nsrCodes** [comment]
Hey @davidalejandroaguilar thanks for bringing this to our attention, this should be fixed in the next version of the desktop app
